name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for changelog generation

    - name: Extract version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linting
      run: npm run lint
      
    - name: Generate changelog
      id: changelog
      run: |
        # Get the previous tag
        PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")

        if [ -z "$PREV_TAG" ]; then
          echo "CHANGELOG=Initial release" >> $GITHUB_OUTPUT
        else
          # Generate changelog from commits since last tag
          CHANGELOG=$(git log --pretty=format:"- %s" ${PREV_TAG}..HEAD | grep -v "^- Merge" | head -20)
          if [ -z "$CHANGELOG" ]; then
            CHANGELOG="- Minor updates and bug fixes"
          fi
          # Escape newlines for GitHub output
          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
          echo "CHANGELOG=$CHANGELOG" >> $GITHUB_OUTPUT
        fi

    - name: Update module.json version
      run: |
        sed -i 's/"version": ".*"/"version": "${{ steps.get_version.outputs.VERSION }}"/' module.json
        
    - name: Create module archive
      run: |
        # Create a clean directory structure for the module
        mkdir -p ring-of-spell-storing

        # Copy all necessary files
        cp module.json ring-of-spell-storing/
        cp -r scripts ring-of-spell-storing/
        cp -r styles ring-of-spell-storing/
        cp -r templates ring-of-spell-storing/
        cp -r lang ring-of-spell-storing/
        cp LICENSE ring-of-spell-storing/
        cp README.md ring-of-spell-storing/
        cp CHANGELOG.md ring-of-spell-storing/

        # Create the zip file
        zip -r ring-of-spell-storing.zip ring-of-spell-storing/
          
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: v${{ steps.get_version.outputs.VERSION }}
        body: |
          # 🎯 Ring of Spell Storing v${{ steps.get_version.outputs.VERSION }}

          A comprehensive implementation of the Ring of Spell Storing magic item for D&D 5th Edition in Foundry VTT.

          ## 📦 Installation

          **Method 1: Direct Installation (Recommended)**
          1. In Foundry VTT, go to **Add-on Modules**
          2. Click **Install Module**
          3. Paste this manifest URL:
          ```
          https://raw.githubusercontent.com/andrewgari/FVTT-Ring-of-Spell-Storing/main/module.json
          ```
          4. Click **Install** and enable the module in your world

          ## ✨ What's New in v${{ steps.get_version.outputs.VERSION }}

          ${{ steps.changelog.outputs.CHANGELOG }}

          ## 🎮 Key Features

          - **Multi-Level Spell Storage**: Store up to 5 levels worth of spells (1st-5th level)
          - **Any Spellcaster Can Contribute**: Not just the ring owner - any spellcaster can store spells
          - **Original Caster Statistics**: Spells retain the original caster's attack bonus and save DC
          - **Intuitive Interface**: Easy-to-use UI for storing, casting, and managing spells
          - **Ring Transfer Support**: Spells remain when the ring changes hands
          - **Foundry Integration**: Seamless integration with D&D 5e system

          ## 🔧 Compatibility

          - **Foundry VTT**: v12+
          - **D&D 5e System**: v3.0.0+

          ## 📚 Documentation

          - [Full Documentation](https://github.com/andrewgari/FVTT-Ring-of-Spell-Storing/blob/main/README.md)
          - [Complete Changelog](https://github.com/andrewgari/FVTT-Ring-of-Spell-Storing/blob/main/CHANGELOG.md)
          - [Report Issues](https://github.com/andrewgari/FVTT-Ring-of-Spell-Storing/issues)
        files: ring-of-spell-storing.zip
        draft: false
        prerelease: false
